"""Datová vrstva nad SQLite (fáze 2) - repository pattern, čisté sqlite3."""

from .bridge import config_pro_mesic, schedule_z_db
from .models import Dvojice, Nedostupnost, PreskocenaSmena, Smena, Uzivatel, Zamestnanec
from .repository import (
    aktivni_zamestnanci,
    aktivni_zamestnanci_v_obdobi,
    deaktivovat_zamestnance,
    dvojice_vsechny,
    inicializovat_schema,
    nedostupnosti_v_obdobi,
    odemknout_smeny,
    opravit_jmeno_zamestnance,
    pridat_dvojici,
    pridat_nedostupnost,
    pridat_zamestnance,
    pripojit,
    pripojit_a_inicializovat,
    smazat_nezamcene_v_obdobi,
    smeny_v_mesici,
    ulozit_rozpis,
    uzivatel_podle_id,
    uzivatel_podle_jmena,
    vytvorit_uzivatele,
    zamknout_smeny,
    zmenit_heslo,
    zrusit_nedostupnost,
)

__all__ = [
    "config_pro_mesic",
    "schedule_z_db",
    "Zamestnanec",
    "Nedostupnost",
    "Smena",
    "PreskocenaSmena",
    "Dvojice",
    "Uzivatel",
    "pripojit",
    "pripojit_a_inicializovat",
    "inicializovat_schema",
    "pridat_zamestnance",
    "deaktivovat_zamestnance",
    "opravit_jmeno_zamestnance",
    "aktivni_zamestnanci",
    "aktivni_zamestnanci_v_obdobi",
    "pridat_nedostupnost",
    "zrusit_nedostupnost",
    "nedostupnosti_v_obdobi",
    "ulozit_rozpis",
    "smeny_v_mesici",
    "zamknout_smeny",
    "odemknout_smeny",
    "smazat_nezamcene_v_obdobi",
    "pridat_dvojici",
    "dvojice_vsechny",
    "vytvorit_uzivatele",
    "uzivatel_podle_jmena",
    "uzivatel_podle_id",
    "zmenit_heslo",
]
